stages:
  - check
  #- initial-checks-and-tests
  - unit-test
  #- secondary-tests
  - integration-test
  - deployment-and-packaging
  - system-test

# Using NIWA IT Provided Shell executor Runner (uses alpine:latest image)
infra-checkov:
  stage: check
  before_script:
    - apk add -U bash
    - chmod +x ./tasks
  script:
    # - bash -c "./tasks checkov_alpine"
    - echo "TODO - infra-checkov"

scripts-shellcheck:
  stage: check
  before_script:
    - apk add -U bash
    - chmod +x ./tasks
  script:
    # - bash -c "./tasks shellcheck_alpine"
    - echo "TODO - scripts-shellcheck"

scripts-unit-tests:
  stage: unit-test
  needs: [scripts-shellcheck]
  before_script:
    - apk add -U bash
    - chmod +x ./tasks
  script:
    # - bash -c "./tasks bats"
    - echo "TODO - scripts-unit-tests"

scripts-package:
  stage: deployment-and-packaging
  needs: [scripts-unit-tests]
  before_script:
    - apk add -U bash
    - chmod +x ./tasks
  script:
    - echo "TODO - scripts-package"

lambda-unit-tests:
  stage: unit-test
  before_script:
  before_script:
    - apk add -U bash
    - chmod +x ./tasks
  script:
    - echo "TODO - lambda-unit-tests"

lambda-integration-tests:
  stage: integration-test
  needs: [lambda-unit-tests]
  before_script:
  before_script:
    - apk add -U bash
    - chmod +x ./tasks
  script:
    - echo "TODO - lambda-integration-tests"

lambda-deployment:
  stage: deployment-and-packaging
  needs: [infra-checkov, lambda-integration-tests]
  before_script:
  before_script:
    - apk add -U bash
    - chmod +x ./tasks
  script:
    - echo "TODO - lambda-deployment"

system-tests:
  stage: system-test
  needs: [scripts-unit-tests, lambda-deployment]
  before_script:
  before_script:
    - apk add -U bash
    - chmod +x ./tasks
  script:
    - echo "TODO - before_image - system-tests"
