# Based on: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Docker.gitlab-ci.yml


shellcheck:
  tags:
    - docker
  # Use the official docker image.
  image: docker:cli
  stage: test
  services:
    - docker:dind
  script:
    - apk add -U bash
    - chmod +x ./tasks
    - bash -c "./tasks shellcheck"
