stages:
  - check
  - lint
  - unit-test
  - integration-test
  - package
  - deploy
  - system-test

# Using NIWA IT Provided Shell executor Runner (uses alpine:latest image)
infra-checkov:
  stage: check
  needs: []
  before_script:
    - apk add -U bash
    - chmod +x ./tasks
  script:
    # - bash -c "./tasks checkov_alpine"
    - sleep 10
    - echo "TODO - infra-checkov"

scripts-shellcheck:
  stage: lint
  needs: []
  before_script:
    - apk add -U bash
    - chmod +x ./tasks
  script:
    # - bash -c "./tasks shellcheck_alpine"
    - sleep 15
    - echo "TODO - scripts-shellcheck"

scripts-unit-tests:
  stage: unit-test
  needs: [scripts-shellcheck]
  before_script:
    - apk add -U bash
    - chmod +x ./tasks
  script:
    # - bash -c "./tasks bats"
    - sleep 17
    - echo "TODO - scripts-unit-tests"

scripts-package:
  stage: package
  needs: [scripts-unit-tests]
  before_script:
    - apk add -U bash
    - chmod +x ./tasks
  script:
    - sleep 13
    - echo "TODO - scripts-package"

lambda-unit-tests:
  stage: unit-test
  needs: []
  before_script:
    - apk add -U bash
    - chmod +x ./tasks
  script:
    - sleep 17
    - echo "TODO - lambda-unit-tests"

lambda-integration-tests:
  stage: integration-test
  needs: [lambda-unit-tests]
  before_script:
  before_script:
    - apk add -U bash
    - chmod +x ./tasks
  script:
    - sleep 13
    - echo "TODO - lambda-integration-tests"

lambda-package:
  stage: package
  needs: [lambda-integration-tests]
  before_script:
  before_script:
    - apk add -U bash
    - chmod +x ./tasks
  script:
    - sleep 15
    - echo "TODO - lambda-package"

lambda-deployment:
  stage: deploy
  needs: [lambda-package, infra-checkov]
  before_script:
  before_script:
    - apk add -U bash
    - chmod +x ./tasks
  script:
    - sleep 15
    - echo "TODO - lambda-deployment"

system-tests:
  stage: system-test
  needs: [scripts-unit-tests, lambda-deployment]
  before_script:
  before_script:
    - apk add -U bash
    - chmod +x ./tasks
  script:
    - sleep 17
    - echo "TODO - before_image - system-tests"
