#!/bin/bash

set -Eeuo pipefail

checkov_image_name="bridgecrew/checkov:3.2.74"

command="$1"
set +u
case "${command}" in
  checkov)
      docker run --rm -v $PWD:/tmp/niwa $checkov_image_name --directory /tmp/niwa/infrastructure
      ;;
  checkov_i)
      # interactive
      docker run --rm --entrypoint=/bin/bash -v $PWD:/tmp/niwa -ti $checkov_image_name -c /bin/bash
      ;;
  shellcheck)
      docker run -t --rm --entrypoint=/bin/sh -v $PWD:/tmp/niwa koalaman/shellcheck-alpine:v0.10.0 -c "shellcheck -e SC2181 /tmp/niwa/upload/data_upload.sh"
      ;;
  bats)
      # remove the log files first
      rm -f ./upload/test/bats/error.txt
      rm -f ./upload/test/bats/success.txt
      rm -f ./upload/test/bats/sync_logs.txt
      rm -f ./upload/test/bats/plan.txt

      # We need the 'file' command for the data upload script. That command
      # is not installed in the docker image. Therefore, we install it below.
      docker run -t --rm --entrypoint=/bin/sh -v $PWD:/tmp/niwa bats/bats:1.11.0 -c "cd /tmp/niwa/upload/test/bats/ && apk add -U file && bats ./*"
      ;;
  _lambda_package)
      # packages the lambda file and its dependencies into a zip file, so
      # it can be uploaded into AWS

      cd processing/
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      ;;
  lambda_package)
      # invokes _lambda_package in Docker

      docker run -t --rm -v $PWD:/tmp/niwa python:3.9.20-bullseye bash -c "cd /tmp/niwa && apt update && apt install -y python3-venv && ./tasks _lambda_package"

      processing_dir=$(realpath ./processing/)
      rm -f "${processing_dir}/lambda_function.zip"
      cd "${processing_dir}/venv/lib/python3.9/site-packages"
      zip -r9 ${processing_dir}/lambda_function.zip .
      cd ${processing_dir}
      zip -g lambda_function.zip lambda_function_mongoDB_schema.py
      ;;
  _lambda_unit_tests)
      # runs pytest unit tests of the Lambda function locally

      # TODO: invoke _lambda_package here instead
      cd processing/
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      pytest
      ;;
  lambda_unit_tests)
      # runs pytest unit tests of the Lambda function in Docker

      docker run -t --rm -v $PWD:/tmp/niwa python:3.9.20-bullseye bash -c "cd /tmp/niwa && apt update && apt install -y python3-venv && ./tasks _lambda_unit_tests"
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
