#
#        file: pytest.ini
# description: This is the default / cannonical pytest configuration file.
#
#
# Some example options:
#
#   [pytest]
#   minversion = 6.0
#   addopts = -v -ra --junitxml=results.xml
#   testpaths = tests example
#
#
# Where:
#
#   minversion            Specify the minimum supported version of pytest
#   testpaths             Specify path to tests - other test files will be ignored.
#   addopts               Always run pytest with the specified runtime options.
#
# Useful Options:
#   -k EXPRESSION         only run tests which match the given substring expression.
#   -q, --quiet           decrease verbosity.
#   -v, --verbose         increase verbosity.
#   -s, --capture=no      show print statements in console
#   -r                    short test summary info.
#   -ra                   Short test summary info excluding passes.   
#   --junitxml=path.xml   create junit results file path.xml
#
#
[pytest]
minversion = 6.0
addopts = -v -ra --junitxml=results.xml
testpaths = tests
