cruises:
  TAN0906:
    images_dir: "R:/National/Datasets/Voyage-Pre-2016/Pre-2010/Data/TAN0906/Tan0906_DTIS images"
    videos_dir: "R:/National/Datasets/Voyage-Pre-2016/Pre-2010/Video/TAN0906_BOI/TAN0906_DTIS-video"
    ofop_dir: "R:/National/Datasets/Voyage-Pre-2016/Pre-2010/Data/TAN0906/TAN0906 OFOP"
    ofop_rerun_dir: "Q:/DTIS_analysis/OFOP reruns by voyage/tan0906_BOI/tan0906_OFOP_reruns"
  TAN0802:
    images_dir: "R:/National/Datasets/Voyage-Pre-2016/Pre-2010/Data/tan0802/DTIS-Images"
    videos_dir: "R:/National/Datasets/Voyage-Pre-2016/Pre-2010/Video/TAN0802_IPY/tan0802_video"
    ofop_dir: "R:/National/Datasets/Voyage-Pre-2016/Pre-2010/Video/TAN0802_IPY/tan0802_OFOP"
    ofop_rerun_dir: "Q:/DTIS_analysis/OFOP reruns by voyage/tan0802_IPY/tan0802_OFOP_reruns/benthic_TAN0802_OFOP_prot"
    
