import os
import io
import json
import yaml
import boto3
import logging
import argparse
import traceback
from PIL import Image, ImageDraw, ImageFont

from botocore.exceptions import ClientError

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

def process_results_file(cfg):
	"""
	Read annotation from results file generated by rekognition inference script
	and annotate results on to image for visualisation
	"""

	try:
		with open(cfg["rekognition_results_file"]) as json_data:
			logger.info(
				f"Successfully read results from "
				f"{cfg['rekognition_results_file']}"
			)

			s3_client = boto3.resource("s3")

			for json_obj in json_data:
				file_result = json.loads(json_obj)
				img = access_image_from_s3(file_result["file_ref"], s3_client)

				draw_bboxes(img, file_result, cfg["local_output_folder"])

				break

	except FileNotFoundError:
		logger.error(
			f"Cannot find rekognition result file "
			f"{cfg['rekognition_results_file']}"
		)
		exit()
	except ClientError as e:
		logger.error(f"Error accessing S3 {e}")
		logger.error(traceback.print_exc())
		exit()


def access_image_from_s3(img_file, s3_client):
	"""
	Stream an image file from S3
	"""
	# Strip file path to bucket and file
	if img_file.startswith("s3://"):
		img_file = img_file[5:]
	img_file = img_file.split("/")
	bucket = img_file[0]
	img_path = "/".join(img_file[1:])


	# Stream file from s3
	logger.info(f"Accessing image file {img_path} from S3 bucket {bucket}")
	s3_obj = s3_client.Object(bucket, img_path)
	s3_response = s3_obj.get()
	stream = io.BytesIO(s3_response["Body"].read())
	img = Image.open(stream)

	return img


def draw_bboxes(img, result, output_folder, line_width=5, font_size=20):
	"""
	Draw rekognition detection onto image
	"""

	# Inprint detected object into image
	img_width, img_height = img.size
	draw = ImageDraw.Draw(img)

	for bbox in result["detections"]:
		label_text = f"{bbox['Label']}: {round(bbox['Confidence'], 2)}%"
		font = ImageFont.truetype("Tahoma.ttf", font_size)
		text_left, text_top, text_right, text_bottom = draw.textbbox(
			(0,0),
			label_text,
			font
		)
		text_width = text_right - text_left
		text_height = text_bottom - text_top

		box_left = img_width * bbox["left"]
		box_width = img_width * bbox["width"]
		box_top = img_height * bbox["top"]
		box_height = img_height * bbox["height"]

		# Draw the bounding box onto the image
		points = (
			(box_left, box_top),
			(box_left + box_width, box_top),
			(box_left+ box_width, box_top + box_height),
			(box_left, box_top + box_height),
			(box_left, box_top)
		)
		draw.line(points, fill="red", width=line_width)

		# Uncomment if text in image is not clear
		# draw.rectangle([
		# 	(box_left + line_width, box_top + line_width),
		# 	(box_left + text_width + line_width, box_top + text_height + line_width)
		# ], fill="black")

		# Add label to bbox in image
		label_left = box_left - line_width
		label_top = box_top - line_width - font_size
		if label_top < 0:
			label_top = box_top + box_height + line_width
		draw.text((label_left, label_top), label_text, fill="red", font=font)

		# Save image to output folder
		filename = result["file_ref"].split("/")[-1]
		save_file = os.path.join(output_folder, filename)
		img.save(save_file)


if __name__ == "__main__":

	parser = argparse.ArgumentParser(
		description="Use trained rekognition model for inference"
	)
	parser.add_argument("-c", required=True, help="Config yaml file")
	args = parser.parse_args()

	try:
		with open(args.c) as cfg_file:
			cfg = yaml.load(cfg_file, Loader=yaml.FullLoader)

		# Make sure output folder exists
		os.makedirs(cfg["local_output_folder"], exist_ok=True)

		process_results_file(cfg)

	except FileNotFoundError:
		logger.info(f"Error loading config file {args.c}")
		logger.error(traceback.print_exc())
	except KeyError:
		logger.error(f"Error reading parameters from config file")
		logger.error(traceback.print_exc())