name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - prod
 
env:
  ENV_NAME: prod

jobs:
  infra-checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Set execute permissions
        run: chmod +x ./tasks
      - name: Set up Bash
        run: sudo apt-get install -y bash
      - name: Run Checkov
        run: |
          chmod +x ./tasks
          ./tasks checkov_alpine
        continue-on-error: true
        if: always()
      - name: Upload Checkov Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: results.xml

  scripts-shellcheck:
    runs-on: ubuntu-latest
    needs: infra-checkov
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Bash
        run: sudo apt-get install -y bash
      - name: Set execute permissions
        run: chmod +x ./tasks
      - name: Run ShellCheck
        run: |
          chmod +x ./tasks
          ./tasks shellcheck_alpine || true
      - name: Upload ShellCheck Report
        uses: actions/upload-artifact@v4
        with:
          name: shellcheck-report
          path: shellcheck_report.xml

  scripts-unit-tests:
    runs-on: ubuntu-latest
    needs: scripts-shellcheck
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set execute permissions
        run: chmod +x ./tasks
      - name: Set up Bash
        run: sudo apt-get install -y bash
      - name: Run Unit Tests
        run: ./tasks bats_alpine
      - name: Upload Unit Test Report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: upload/test/bats/report.xml

  lambda-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set execute permissions
        run: chmod +x ./tasks
      - name: Set up Bash
        run: sudo apt-get install -y bash
      - name: Run Lambda Unit Tests
        run: ./tasks lambda_unit_tests_alpine
      - name: Upload Lambda Unit Test Report
        uses: actions/upload-artifact@v4
        with:
          name: lambda-unit-test-report
          path: processing/report.xml

  lambda-integration-tests:
    runs-on: ubuntu-latest
    needs: lambda-unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Bash
        run: sudo apt-get install -y bash
      - name: Set execute permissions
        run: chmod +x ./tasks
      - name: Run Lambda Integration Tests
        run: |
          chmod +x ./tasks
          echo "TODO - lambda-integration-tests"
          exit 1
        continue-on-error: true

  lambda-package:
    runs-on: ubuntu-latest
    needs: lambda-integration-tests
    environment: dev
    container:
      image: python:3.12-bookworm
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install zip utility
        run: apt-get update && apt-get install -y zip
      - name: Make packaging script executable
        run: chmod +x ./lambda/scripts/create_pkg.sh

      # Ingress Lambda
      - name: Cache ingress Lambda zip
        id: ingress-cache
        uses: actions/cache@v3
        with:
          path: infrastructure/2-seafloor-data/lambda_ingress.zip
          key: ingress-${{ hashFiles('lambda/lambda_functions/ingress/lambda_function_mongoDB_schema.py') }}
      - name: Package ingress Lambda
        if: steps.ingress-cache.outputs.cache-hit != 'true'
        shell: bash
        run: ./lambda/scripts/create_pkg.sh $PWD/lambda ingress python3
      - name: Skip ingress packaging
        if: steps.ingress-cache.outputs.cache-hit == 'true'
        run: echo "Cache hit — skipping ingress Lambda packaging."
      # Media Convert Lambda
      - name: Cache media_convert Lambda zip
        id: media-cache
        uses: actions/cache@v3
        with:
          path: infrastructure/2-seafloor-data/lambda_media_convert.zip
          key: media-${{ hashFiles('lambda/lambda_functions/media_convert/lambda_function_media_convert.py') }}
      - name: Package media_convert Lambda
        if: steps.media-cache.outputs.cache-hit != 'true'
        shell: bash
        run: ./lambda/scripts/create_pkg.sh $PWD/lambda media_convert python3
      - name: Skip media_convert packaging
        if: steps.media-cache.outputs.cache-hit == 'true'
        run: echo "Cache hit — skipping media_convert Lambda packaging."
      # Pretrained Annotation Lambda
      - name: Cache pretrained_annotation Lambda zip
        id: pretrained-cache
        uses: actions/cache@v3
        with:
          path: infrastructure/2-seafloor-data/lambda_pretrained_annotation.zip
          key: pretrained-${{ hashFiles('lambda/lambda_functions/pretrained_annotation/lambda_function_pretrained_annotation.py') }}
      - name: Package pretrained_annotation Lambda
        if: steps.pretrained-cache.outputs.cache-hit != 'true'
        shell: bash
        run: ./lambda/scripts/create_pkg.sh $PWD/lambda pretrained_annotation python3
      - name: Skip pretrained_annotation packaging
        if: steps.pretrained-cache.outputs.cache-hit == 'true'
        run: echo "Cache hit — skipping pretrained_annotation Lambda packaging."
      # biigle_anno_retrieval
      - name: Cache biigle_anno_retrieval Lambda zip
        id: biigle-cache
        uses: actions/cache@v3
        with:
          path: infrastructure/2-seafloor-data/lambda_biigle_anno_retrieval.zip
          key: biigle-${{ hashFiles('lambda/lambda_functions/biigle_anno_retrieval/lambda_function_biigle_anno_retrieval.py') }}
      - name: Package biigle_anno_retrieval Lambda
        if: steps.biigle-cache.outputs.cache-hit != 'true'
        shell: bash
        run: ./lambda/scripts/create_pkg.sh $PWD/lambda biigle_anno_retrieval python3
      - name: Skip biigle_anno_retrieval packaging
        if: steps.biigle-cache.outputs.cache-hit == 'true'
        run: echo "Cache hit — skipping biigle_anno_retrieval Lambda packaging."
      # taxonomy
      - name: Cache taxonomy Lambda zip
        id: taxonomy-cache
        uses: actions/cache@v3
        with:
          path: infrastructure/2-seafloor-data/lambda_taxonomy.zip
          key: taxonomy-${{ hashFiles('lambda/lambda_functions/taxonomy/lambda_function_taxonomy.py') }}
      - name: Package taxonomy Lambda
        if: steps.taxonomy-cache.outputs.cache-hit != 'true'
        shell: bash
        run: ./lambda/scripts/create_pkg.sh $PWD/lambda taxonomy python3
      - name: Skip taxonomy packaging
        if: steps.taxonomy-cache.outputs.cache-hit == 'true'
        run: echo "Cache hit — skipping taxonomy Lambda packaging."

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-zips
          path: infrastructure/2-seafloor-data/*.zip

  terraform-deployment:
    runs-on: ubuntu-latest
    needs: lambda-package
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-zips
          path: ./lambda-zips
      - name: Move lambda zips
        shell: bash
        run: |
          find ./lambda-zips -name "*.zip" -exec mv {} infrastructure/2-seafloor-data/ \;
          ls -l infrastructure/2-seafloor-data/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6
      - name: Terraform Init
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          echo "access key id (partial): ${AWS_ACCESS_KEY_ID:0:4}"
          echo "secret access key (partial): ${AWS_SECRET_ACCESS_KEY:0:4}"
          echo "mongo uri (partial): ${MONGO_URI:53:63}"
          echo "env name: ${ENV_NAME}"
          cd infrastructure/2-seafloor-data
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "AWS Account ID (partial): ${AWS_ACCOUNT_ID:0:4}"
          terraform_state_bucket="data-platform-dtis-${ENV_NAME}-${AWS_ACCOUNT_ID}-terraform-state"
          terraform_key="niwa-dtis-ofop/${ENV_NAME}/${ENV_NAME}.tfstate"
          echo "Running terraform init with bucket: ${terraform_state_bucket}"
          echo "and key: ${terraform_key}"
          terraform init -reconfigure \
            -backend-config="bucket=${terraform_state_bucket}" \
            -backend-config="key=${terraform_key}"
      - name: Terraform Plan
        run: |
          cd infrastructure/2-seafloor-data
          terraform plan -out=plan.tfplan \
            -var="mongo_uri=${{secrets.MONGO_URI}}"
      - name: Terraform Apply
        run: |
          cd infrastructure/2-seafloor-data
          terraform apply -auto-approve plan.tfplan

  system-tests:
    runs-on: ubuntu-latest
    needs: [scripts-unit-tests, terraform-deployment]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Bash
        run: sudo apt-get install -y bash
      - name: Set execute permissions
        run: chmod +x ./tasks
      - name: Run System Tests
        run: |
          chmod +x ./tasks
          echo "TODO - system-tests"
          exit 1
        continue-on-error: true